name: Publish Python Package to GitHub Packages

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Build and publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -m build
        python -m twine upload --repository-url https://maven.pkg.github.com/${{ github.repository }} dist/*
        # The GITHUB_TOKEN is automatically provided to the workflow
        # and has the necessary permissions to publish to GitHub Packages